version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/e2e"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "nilwurtz"
    auto-merge:
      enabled: true
      strategy: "merge"

  - package-ecosystem: "maven"
    directory: "/wiremock-graphql-extension"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "nilwurtz"
    auto-merge:
      enabled: true
      strategy: "merge"