name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-make:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - uses: getgauge/setup-gauge@master
        with:
          gauge-version: '1.4.3'
          gauge-plugins: java, html-report

      - name: Run unit test and install
        run: make install
        working-directory: e2e

      - name: Run unit test and install
        run: make clean test_compile run
        working-directory: e2e
