name: Build and Release
description: Build jar and release it to github release.

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Get Target version
        id: version
        run: |-
          VERSION=$(mvn help:evaluate -Dexpression=project.version -B | grep -v '\[INFO\]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and package JAR
        run: mvn -f wiremock-graphql-extension clean package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wiremock-graphql-extension/target/wiremock-graphql-extension-*.jar
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
